package org.example.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-24T12:05:32.472+02:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/customer/", name = "CustomerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerPortType {

    @WebMethod(action = "http://www.example.org/customer/lookupCustomer")
    @WebResult(name = "lookupCustomerResponse", targetNamespace = "http://www.example.org/customer/", partName = "out")
    public LookupCustomerResponseType lookupCustomer(
        @WebParam(partName = "in", name = "lookupCustomerRequest", targetNamespace = "http://www.example.org/customer/")
        LookupCustomerRequestType in
    );
}
