package org.example.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-24T12:05:32.502+02:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "CustomerService",
                  wsdlLocation = "file:\\C:\\Users\\dule\\redHatWorkspace\\zadatak3Spring\\src\\main\\resources\\wsdl\\CustomerService.wsdl",
                  targetNamespace = "http://www.example.org/customer/")
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/customer/", "CustomerService");
    public final static QName CustomerPort = new QName("http://www.example.org/customer/", "CustomerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:\\C:\\Users\\dule\\redHatWorkspace\\zadatak3SpringDsl\\src\\main\\resources\\wsdl\\CustomerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:\\C:\\Users\\dule\\redHatWorkspace\\zadatak3SpringDsl\\src\\main\\resources\\wsdl\\CustomerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features );
    }

    public CustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerPortType
     */
    @WebEndpoint(name = "CustomerPort")
    public CustomerPortType getCustomerPort() {
        return super.getPort(CustomerPort, CustomerPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerPortType
     */
    @WebEndpoint(name = "CustomerPort")
    public CustomerPortType getCustomerPort(WebServiceFeature... features) {
        return super.getPort(CustomerPort, CustomerPortType.class, features);
    }

}
